# Generated by Django 5.2.5 on 2025-08-26 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('school', 'School Website'), ('hospital', 'Hospital Website'), ('ecommerce', 'E-Commerce Website'), ('marketing', 'Marketing Website'), ('portfolio', 'Portfolio Website'), ('blog', 'Blog Website'), ('custom', 'Custom Solution')], default='custom', max_length=20)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('proposal', 'Proposal'), ('in_progress', 'In Progress'), ('review', 'Review'), ('completed', 'Completed'), ('maintenance', 'Maintenance')], default='inquiry', max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hosting_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
