# Generated by Django 5.2.5 on 2025-08-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectattachment_projectcollaborator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(null=True),
        ),
    ]
