# Generated by Django 5.2.5 on 2025-08-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
