# Generated by Django 5.2.1 on 2025-09-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogtag_websiteanalytics_blogpost_client_lead_and_more'),
        ('projects', '0007_project_collaborators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('cms', 'CMS'), ('framework', 'Framework'), ('tool', 'Development Tool'), ('hosting', 'Hosting/Deployment'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.CharField(help_text='Font Awesome or DevIcon class name', max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('comment', 'View & Comment'), ('collaborate', 'Full Collaboration')], default='view', max_length=20)),
                ('client_access_enabled', models.BooleanField(default=True)),
                ('access_granted_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to='core.client')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_access', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_gallery/')),
                ('image_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('mockup', 'Mockup'), ('process', 'Process Image'), ('before_after', 'Before/After'), ('feature', 'Feature Highlight'), ('other', 'Other')], default='screenshot', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_load_time', models.DecimalField(blank=True, decimal_places=2, help_text='Seconds', max_digits=5, null=True)),
                ('lighthouse_score', models.PositiveSmallIntegerField(blank=True, help_text='0-100', null=True)),
                ('mobile_friendly', models.BooleanField(default=True)),
                ('traffic_increase', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage', max_digits=5, null=True)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage', max_digits=5, null=True)),
                ('bounce_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage', max_digits=5, null=True)),
                ('development_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('lines_of_code', models.PositiveIntegerField(blank=True, null=True)),
                ('seo_score', models.PositiveSmallIntegerField(blank=True, help_text='0-100', null=True)),
                ('keywords_ranking', models.PositiveIntegerField(blank=True, help_text='Number of keywords in top 10', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_feedback', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('client_name', models.CharField(max_length=255)),
                ('client_position', models.CharField(blank=True, max_length=255, null=True)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='project_testimonials/')),
                ('is_approved', models.BooleanField(default=True)),
                ('featured_quote', models.CharField(blank=True, help_text='Short quote for highlights', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tool', 'Development Tool')], default='secondary', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='projects.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.technology')),
            ],
            options={
                'unique_together': {('project', 'technology')},
            },
        ),
    ]
