# Generated by Django 5.2.1 on 2025-09-02 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_technology_clientproject_projectimage_projectmetrics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcollaborator',
            options={'ordering': ['-is_lead', 'added_at']},
        ),
        migrations.AddField(
            model_name='projectcollaborator',
            name='is_lead',
            field=models.BooleanField(default=False, help_text='Is this collaborator the project lead?'),
        ),
        migrations.AlterField(
            model_name='projectcollaborator',
            name='role',
            field=models.CharField(blank=True, choices=[('project_manager', 'Project Manager'), ('lead_developer', 'Lead Developer'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('ui_ux_designer', 'UI/UX Designer'), ('qa_tester', 'Quality Assurance'), ('devops_engineer', 'DevOps Engineer'), ('consultant', 'Consultant'), ('collaborator', 'Collaborator')], default='collaborator', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectcollaborator',
            unique_together={('project', 'user')},
        ),
    ]
