# Generated by Django 5.2.5 on 2025-08-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pricingplan'),
        ('projects', '0005_alter_project_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='project_logs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
