# Generated by Django 5.2.5 on 2025-08-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activitylog_project_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
