# Generated by Django 5.2.5 on 2025-08-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teammember_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to='team/hero/'),
        ),
    ]
