# Generated by Django 5.2.1 on 2025-09-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blogpost_read_time_blogpost_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtag',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='blogtag',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('design', 'Design'), ('mobile', 'Mobile'), ('infrastructure', 'Infrastructure'), ('ai', 'AI & ML'), ('security', 'Security'), ('quality', 'Quality'), ('architecture', 'Architecture'), ('crypto', 'Blockchain & Crypto'), ('optimization', 'Optimization'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='icon',
            field=models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fas fa-code')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
