# Generated by Django 5.2.1 on 2025-09-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_enhance_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter skills separated by commas', null=True),
        ),
    ]
