# Generated by Django 5.2.1 on 2025-09-03 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teammember_skills'),
    ]

    operations = [
    ]
