# Generated by Django 5.2.5 on 2025-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20250903_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
