# Generated by Django 5.2.5 on 2025-09-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesetting_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(choices=[('website', 'Website Development'), ('ecommerce', 'E-commerce Solution'), ('webapp', 'Web Application'), ('mobile', 'Mobile App'), ('redesign', 'Website Redesign'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('budget', models.CharField(blank=True, choices=[('under-5k', 'Under $5,000'), ('5k-10k', '$5,000 - $10,000'), ('10k-25k', '$10,000 - $25,000'), ('25k-50k', '$25,000 - $50,000'), ('50k-plus', '$50,000+')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quote Sent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for follow-up', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Quick Inquiry',
                'verbose_name_plural': 'Quick Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
