# Generated by Django 5.2.1 on 2025-09-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_quickinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Enable this to put the site in maintenance mode. Only admins will be able to access the site.'),
        ),
    ]
