from django.core.management.base import BaseCommand
from services.models import Service

class Command(BaseCommand):
    help = 'Populate the database with sample services.'

    def handle(self, *args, **kwargs):
        sample_services = [
            # Web Development
            {
                'name': 'Custom Web Development',
                'category': 'web_development',
                'short_description': 'Bespoke websites tailored to your needs.',
                'description': 'We build custom, scalable, and secure websites for businesses, schools, and organizations.',
                'base_price': 3000.00,
                'icon': 'code',
                'features': 'Responsive design\nSEO optimized\nFast loading\nCustom integrations',
                'is_featured': True,
                'display_order': 1,
            },
            {
                'name': 'API Development',
                'category': 'web_development',
                'short_description': 'Robust APIs for your web and mobile apps.',
                'description': 'We create RESTful and GraphQL APIs for seamless integrations.',
                'base_price': 1800.00,
                'icon': 'project-diagram',
                'features': 'REST/GraphQL\nAuthentication\nDocumentation\nIntegration support',
                'is_featured': False,
                'display_order': 2,
            },
            {
                'name': 'Landing Page Development',
                'category': 'web_development',
                'short_description': 'High-converting landing pages.',
                'description': 'We build landing pages optimized for conversions and lead capture.',
                'base_price': 800.00,
                'icon': 'file-alt',
                'features': 'A/B testing\nAnalytics\nFast load\nMobile optimized',
                'is_featured': False,
                'display_order': 3,
            },
            # Web Design
            {
                'name': 'Professional Web Design',
                'category': 'web_design',
                'short_description': 'Modern, user-friendly web design services.',
                'description': 'Our design team creates beautiful, intuitive, and brand-aligned websites.',
                'base_price': 2000.00,
                'icon': 'paint-brush',
                'features': 'UI/UX design\nBranding\nMobile-first\nPrototyping',
                'is_featured': True,
                'display_order': 4,
            },
            {
                'name': 'Logo & Brand Design',
                'category': 'web_design',
                'short_description': 'Unique logos and brand identity.',
                'description': 'We design memorable logos and cohesive brand systems.',
                'base_price': 900.00,
                'icon': 'palette',
                'features': 'Logo design\nBrand guidelines\nColor palette\nTypography',
                'is_featured': False,
                'display_order': 5,
            },
            {
                'name': 'UI/UX Audit',
                'category': 'web_design',
                'short_description': 'Improve your site usability.',
                'description': 'We audit your site for usability and provide actionable recommendations.',
                'base_price': 600.00,
                'icon': 'search-plus',
                'features': 'Heuristic review\nUser testing\nAccessibility\nReport',
                'is_featured': False,
                'display_order': 6,
            },
            # E-Commerce
            {
                'name': 'E-Commerce Solutions',
                'category': 'ecommerce',
                'short_description': 'Sell online with a secure, scalable store.',
                'description': 'We develop e-commerce platforms with payment integration, inventory, and analytics.',
                'base_price': 4000.00,
                'icon': 'shopping-cart',
                'features': 'Payment gateway\nInventory management\nOrder tracking\nAnalytics',
                'is_featured': True,
                'display_order': 7,
            },
            {
                'name': 'Shopify Store Setup',
                'category': 'ecommerce',
                'short_description': 'Launch your Shopify store fast.',
                'description': 'We set up and customize your Shopify store for your brand.',
                'base_price': 1200.00,
                'icon': 'store',
                'features': 'Theme setup\nPayment config\nShipping\nApps integration',
                'is_featured': False,
                'display_order': 8,
            },
            {
                'name': 'WooCommerce Integration',
                'category': 'ecommerce',
                'short_description': 'Add e-commerce to your WordPress site.',
                'description': 'We integrate WooCommerce for seamless online sales.',
                'base_price': 1000.00,
                'icon': 'wordpress',
                'features': 'Product catalog\nCart & checkout\nCoupons\nReports',
                'is_featured': False,
                'display_order': 9,
            },
            # CMS
            {
                'name': 'Content Management Systems',
                'category': 'cms',
                'short_description': 'Easily manage your website content.',
                'description': 'We implement and customize CMS solutions like WordPress, Wagtail, and Django CMS.',
                'base_price': 1800.00,
                'icon': 'edit',
                'features': 'Easy editing\nUser roles\nMedia management\nSEO tools',
                'is_featured': False,
                'display_order': 10,
            },
            {
                'name': 'WordPress Customization',
                'category': 'cms',
                'short_description': 'Custom themes and plugins for WordPress.',
                'description': 'We build custom themes and plugins to extend WordPress functionality.',
                'base_price': 900.00,
                'icon': 'wordpress-simple',
                'features': 'Theme dev\nPlugin dev\nSecurity\nPerformance',
                'is_featured': False,
                'display_order': 11,
            },
            {
                'name': 'Wagtail CMS Solutions',
                'category': 'cms',
                'short_description': 'Flexible CMS for Django projects.',
                'description': 'We implement Wagtail for powerful, flexible content management.',
                'base_price': 1500.00,
                'icon': 'feather-alt',
                'features': 'StreamField\nImage library\nWorkflows\nSEO',
                'is_featured': False,
                'display_order': 12,
            },
            # SEO
            {
                'name': 'SEO Optimization',
                'category': 'seo',
                'short_description': 'Improve your search engine ranking.',
                'description': 'Our SEO experts help your site rank higher and attract more visitors.',
                'base_price': 1200.00,
                'icon': 'search',
                'features': 'Keyword research\nOn-page SEO\nTechnical SEO\nReporting',
                'is_featured': False,
                'display_order': 13,
            },
            {
                'name': 'Local SEO',
                'category': 'seo',
                'short_description': 'Get found in your local area.',
                'description': 'We optimize your site for local search and Google My Business.',
                'base_price': 700.00,
                'icon': 'map-marker-alt',
                'features': 'Google My Business\nLocal citations\nReviews\nMaps',
                'is_featured': False,
                'display_order': 14,
            },
            {
                'name': 'SEO Audit',
                'category': 'seo',
                'short_description': 'Comprehensive SEO site audit.',
                'description': 'We audit your site and provide a detailed SEO improvement plan.',
                'base_price': 500.00,
                'icon': 'clipboard-check',
                'features': 'Site crawl\nBacklink check\nCompetitor analysis\nAction plan',
                'is_featured': False,
                'display_order': 15,
            },
            # Maintenance
            {
                'name': 'Website Maintenance',
                'category': 'maintenance',
                'short_description': 'Keep your website secure and up-to-date.',
                'description': 'We offer ongoing maintenance, updates, and support for your website.',
                'base_price': 500.00,
                'icon': 'tools',
                'features': 'Security updates\nBackups\nPerformance monitoring\nBug fixes',
                'is_featured': False,
                'display_order': 16,
            },
            {
                'name': 'Performance Optimization',
                'category': 'maintenance',
                'short_description': 'Speed up your website.',
                'description': 'We optimize your site for faster load times and better user experience.',
                'base_price': 400.00,
                'icon': 'tachometer-alt',
                'features': 'Caching\nImage optimization\nMinification\nLazy loading',
                'is_featured': False,
                'display_order': 17,
            },
            {
                'name': 'Security Monitoring',
                'category': 'maintenance',
                'short_description': 'Protect your site from threats.',
                'description': 'We monitor and secure your site against malware and attacks.',
                'base_price': 350.00,
                'icon': 'shield-alt',
                'features': 'Malware scan\nFirewall\nAlerts\nRemediation',
                'is_featured': False,
                'display_order': 18,
            },
            # Hosting
            {
                'name': 'Web Hosting',
                'category': 'hosting',
                'short_description': 'Reliable and fast web hosting services.',
                'description': 'We provide managed hosting solutions for all types of websites.',
                'base_price': 150.00,
                'icon': 'server',
                'features': '99.9% uptime\nSSL certificates\nDaily backups\nScalable plans',
                'is_featured': False,
                'display_order': 19,
            },
            {
                'name': 'Cloud Hosting',
                'category': 'hosting',
                'short_description': 'Scalable cloud hosting for growth.',
                'description': 'We set up and manage cloud hosting on AWS, Azure, or GCP.',
                'base_price': 300.00,
                'icon': 'cloud',
                'features': 'Auto-scaling\nLoad balancing\nBackups\nMonitoring',
                'is_featured': False,
                'display_order': 20,
            },
            {
                'name': 'Domain Management',
                'category': 'hosting',
                'short_description': 'Domain registration and management.',
                'description': 'We handle domain registration, renewals, and DNS setup.',
                'base_price': 50.00,
                'icon': 'globe',
                'features': 'Domain search\nDNS setup\nRenewals\nTransfers',
                'is_featured': False,
                'display_order': 21,
            },
            # Consultation
            {
                'name': 'IT Consultation',
                'category': 'consultation',
                'short_description': 'Expert advice for your digital strategy.',
                'description': 'Our consultants help you plan, launch, and grow your digital presence.',
                'base_price': 100.00,
                'icon': 'comments',
                'features': 'Strategy sessions\nTechnology audit\nRoadmapping\nTraining',
                'is_featured': False,
                'display_order': 22,
            },
            {
                'name': 'Digital Transformation',
                'category': 'consultation',
                'short_description': 'Transform your business for the digital age.',
                'description': 'We guide your business through digital transformation and process automation.',
                'base_price': 200.00,
                'icon': 'sync',
                'features': 'Process automation\nCloud migration\nChange management\nTraining',
                'is_featured': False,
                'display_order': 23,
            },
            {
                'name': 'Technology Audit',
                'category': 'consultation',
                'short_description': 'Assess your current tech stack.',
                'description': 'We audit your technology and provide recommendations for improvement.',
                'base_price': 150.00,
                'icon': 'search-dollar',
                'features': 'Infrastructure review\nSecurity check\nCost analysis\nReport',
                'is_featured': False,
                'display_order': 24,
            },
        ]

        created = 0
        for data in sample_services:
            obj, was_created = Service.objects.get_or_create(
                name=data['name'],
                defaults=data
            )
            if was_created:
                created += 1
        self.stdout.write(self.style.SUCCESS(f"{created} sample services added."))
