from django.core.management.base import BaseCommand
from projects.models import Project
from django.utils import timezone
import random

class Command(BaseCommand):
    help = 'Populate the database with sample projects for the portfolio.'

    def handle(self, *args, **kwargs):
        sample_projects = [
            {
                'client_name': 'Dr. Sarah Johnson',
                'client_email': 'sarah.johnson@example.com',
                'client_phone': '555-1234',
                'organization_name': 'Lincoln High School',
                'title': 'Lincoln High School Website',
                'description': 'A modern, accessible website for a leading educational institution, featuring event calendars, news, and parent portals.',
                'project_type': 'school',
                'requirements': 'Responsive design, CMS integration, event calendar, parent portal',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 5000.00,
                'domain_name': 'lincolnhigh.edu',
                'hosting_provider': 'Bluehost',
            },
            {
                'client_name': 'Dr. Robert Williams',
                'client_email': 'robert.williams@example.com',
                'client_phone': '555-5678',
                'organization_name': 'City General Hospital',
                'title': 'City General Hospital Portal',
                'description': 'A secure, patient-friendly portal for a busy city hospital, including appointment scheduling and patient records.',
                'project_type': 'hospital',
                'requirements': 'Patient portal, appointment scheduling, secure login',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 12000.00,
                'domain_name': 'citygeneralhospital.com',
                'hosting_provider': 'AWS',
            },
            {
                'client_name': 'Michael Chen',
                'client_email': 'michael.chen@example.com',
                'client_phone': '555-8765',
                'organization_name': 'Urban Styles',
                'title': 'Urban Styles E-Commerce',
                'description': 'A stylish, conversion-optimized e-commerce platform with secure payment processing and inventory management.',
                'project_type': 'ecommerce',
                'requirements': 'E-commerce, payment gateway, inventory management',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 8000.00,
                'domain_name': 'urbanstyles.com',
                'hosting_provider': 'Shopify',
            },
            {
                'client_name': 'Emily Davis',
                'client_email': 'emily.davis@example.com',
                'client_phone': '555-4321',
                'organization_name': 'Bright Marketing',
                'title': 'Bright Marketing Website',
                'description': 'A lead-generation marketing website with analytics integration and SEO optimization.',
                'project_type': 'marketing',
                'requirements': 'SEO, analytics, lead forms',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 4000.00,
                'domain_name': 'brightmarketing.com',
                'hosting_provider': 'GoDaddy',
            },
            {
                'client_name': 'Alex Carter',
                'client_email': 'alex.carter@example.com',
                'client_phone': '555-2468',
                'organization_name': 'Carter Portfolio',
                'title': 'Carter Portfolio Website',
                'description': 'A beautiful, responsive portfolio website to showcase creative work and achievements.',
                'project_type': 'portfolio',
                'requirements': 'Portfolio gallery, blog, contact form',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 2500.00,
                'domain_name': 'alexcarter.com',
                'hosting_provider': 'Netlify',
            },

            {
                'client_name': 'Samantha Lee',
                'client_email': 'samantha.lee@example.com',
                'client_phone': '555-3344',
                'organization_name': 'Green Valley School',
                'title': 'Green Valley School Redesign',
                'description': 'A fresh redesign for a K-12 school, including a new events system and staff directory.',
                'project_type': 'school',
                'requirements': 'Events, staff directory, mobile-first',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 6000.00,
                'domain_name': 'greenvalleyschool.org',
                'hosting_provider': 'Bluehost',
            },
            {
                'client_name': 'John Smith',
                'client_email': 'john.smith@example.com',
                'client_phone': '555-7788',
                'organization_name': 'Smith Dental Clinic',
                'title': 'Smith Dental Clinic Portal',
                'description': 'A patient portal for appointment booking and dental records.',
                'project_type': 'hospital',
                'requirements': 'Booking, patient records, reminders',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 3500.00,
                'domain_name': 'smithdental.com',
                'hosting_provider': 'AWS',
            },
            {
                'client_name': 'Olivia Brown',
                'client_email': 'olivia.brown@example.com',
                'client_phone': '555-9988',
                'organization_name': 'Brown Boutique',
                'title': 'Brown Boutique Online Store',
                'description': 'A boutique e-commerce site with product catalog and payment integration.',
                'project_type': 'ecommerce',
                'requirements': 'Product catalog, payment, shipping',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 7000.00,
                'domain_name': 'brownboutique.com',
                'hosting_provider': 'Shopify',
            },
            {
                'client_name': 'David Kim',
                'client_email': 'david.kim@example.com',
                'client_phone': '555-1122',
                'organization_name': 'Kim Digital',
                'title': 'Kim Digital Marketing Site',
                'description': 'A marketing website with blog and lead capture forms.',
                'project_type': 'marketing',
                'requirements': 'Blog, lead forms, analytics',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 4500.00,
                'domain_name': 'kimdigital.com',
                'hosting_provider': 'GoDaddy',
            },
            {
                'client_name': 'Priya Patel',
                'client_email': 'priya.patel@example.com',
                'client_phone': '555-5566',
                'organization_name': 'Patel Creative',
                'title': 'Patel Creative Portfolio',
                'description': 'A creative portfolio with gallery and testimonials.',
                'project_type': 'portfolio',
                'requirements': 'Gallery, testimonials, contact',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 3200.00,
                'domain_name': 'patelcreative.com',
                'hosting_provider': 'Netlify',
            },
            {
                'client_name': 'Lucas White',
                'client_email': 'lucas.white@example.com',
                'client_phone': '555-7789',
                'organization_name': 'White Custom Apps',
                'title': 'White Custom Web App',
                'description': 'A custom web application for internal business management.',
                'project_type': 'custom',
                'requirements': 'User management, reporting, dashboard',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 15000.00,
                'domain_name': 'whitecustomapps.com',
                'hosting_provider': 'Heroku',
            },
            {
                'client_name': 'Sophia Green',
                'client_email': 'sophia.green@example.com',
                'client_phone': '555-3345',
                'organization_name': 'Green Blog',
                'title': 'Green Blog Platform',
                'description': 'A blog platform with categories, tags, and comments.',
                'project_type': 'blog',
                'requirements': 'Categories, tags, comments',
                'start_date': timezone.now().date(),
                'deadline': timezone.now().date(),
                'completed_date': timezone.now().date(),
                'status': 'completed',
                'budget': 2800.00,
                'domain_name': 'greenblog.com',
                'hosting_provider': 'Netlify',
            },
        ]

        created = 0
        for data in sample_projects:
            obj, was_created = Project.objects.get_or_create(
                title=data['title'],
                defaults=data
            )
            if was_created:
                created += 1
        self.stdout.write(self.style.SUCCESS(f"{created} sample projects added."))
